on:
  issue_comment:
    types: [ created ]
name: Commented Pull Request
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            bucket
            deprecated
            bin
            Scoop-Bucket.Tests.ps1
          sparse-checkout-cone-mode: false
      - name: PullRequestHandler
        uses: ScoopInstaller/GithubActions@main
        if: startsWith(github.event.comment.body, '/verify')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
